apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-k8s-fe-deployment
  labels:
    app: demo-k8s-fe
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # do not delete pods before adding them (surge)
      maxSurge: 2  # when updating append two new pods every time
  selector:
    matchLabels:
      app: demo-k8s-fe
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-k8s-fe
    spec:
      containers:
      - name: api
        image: fargozhu/demo-k8s-fe:v5
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
